from enum import StrEnum

class ErrorCode(StrEnum):
    BLOB_UNKNOWN = 'BLOB_UNKNOWN'
    BLOB_UPLOAD_INVALID = 'BLOB_UPLOAD_INVALID'
    BLOB_UPLOAD_UNKNOWN = 'BLOB_UPLOAD_UNKNOWN'
    DIGEST_INVALID = 'DIGEST_INVALID'
    MANIFEST_BLOB_UNKNOWN = 'MANIFEST_BLOB_UNKNOWN'
    MANIFEST_INVALID = 'MANIFEST_INVALID'
    MANIFEST_UNKNOWN = 'MANIFEST_UNKNOWN'
    NAME_INVALID = 'NAME_INVALID'
    NAME_UNKNOWN = 'NAME_UNKNOWN'
    SIZE_INVALID = 'SIZE_INVALID'
    UNAUTHORIZED = 'UNAUTHORIZED'
    DENIED = 'DENIED'
    UNSUPPORTED = 'UNSUPPORTED'
    TOOMANYREQUESTS = 'TOOMANYREQUESTS'